### ISSUE TITLE
Explanation for Lift Tests

### ISSUE THREAD

**Issue by BrianMiner** [pymc-labs/pymc-marketing#1071]
I have read the description of the list tests, e.g. [here](https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_lift_test.html)
but its not clear to me how adding a distribution like gamma to the likelihood is able to calibrate the saturation curves. Is there any descriptions of example how this works?

**Comment by wd60622** [comment]
Will respond tomorrow

**Comment by wd60622** [comment]
Hi @BrianMiner,

The implementation comes from the observation that there doesn't have to be exact measurements of the saturation curve in order to estimate the parameters of it. 

That is, with $f(x; \\theta)$ is the saturation curve and $\\theta$ is the parameter(s) of the curve then you can use $f(x_1; \\theta) - f(x_0; \\theta)$ to estimate the parameters of the curve. That is what is happening in the `add_saturation_observations` function (There an example in the docstring).

A distribution comes into play because the lift test that are observed are not exact measurements and are expected to have some noise. The Gmma distribution is used to model this noise by default. This choice is partly arbitrary but makes more sense as the saturation curve is montonic making increase in media correspond to an increase in target (positive lift). A decrease in media is assumed to have a negative lift.

Let me know if that helps. I can provide some more details if you have more specific questions.

**Comment by wd60622** [comment]
Hi @BrianMiner,

The implementation comes from the observation that there doesn't have to be exact measurements of the saturation curve in order to estimate the parameters of it. 

That is, with $f(x; \\theta)$ is the saturation curve and $\\theta$ is the parameter(s) of the curve then you can use $f(x_1; \\theta) - f(x_0; \\theta)$ to estimate the parameters of the curve. That is what is happening in the [`add_saturation_observations`](https://www.pymc-marketing.io/en/stable/api/generated/pymc_marketing.mmm.lift_test.add_saturation_observations.html#pymc_marketing.mmm.lift_test.add_saturation_observations) function (There an example in the docstring).

A distribution comes into play because the lift test that are observed are not exact measurements and are expected to have some noise. The Gmma distribution is used to model this noise by default. This choice is partly arbitrary but makes more sense as the saturation curve is montonic making increase in media correspond to an increase in target (positive lift). A decrease in media is assumed to have a negative lift.

Let me know if that helps. I can provide some more details if you have more specific questions.

**Comment by wd60622** [comment]
Hi @BrianMiner,

The implementation comes from the observation that there doesn't have to be exact measurements of the saturation curve in order to estimate the parameters of it. 

That is, with $f(x; \\theta)$ is the saturation curve and $\\theta$ is the parameter(s) of the curve then you can use $f(x_1; \\theta) - f(x_0; \\theta)$ to estimate the parameters of the curve. That is what is happening in the [`add_saturation_observations`](https://www.pymc-marketing.io/en/stable/api/generated/pymc_marketing.mmm.lift_test.add_saturation_observations.html#pymc_marketing.mmm.lift_test.add_saturation_observations) function (There an example in the docstring).

A distribution comes into play because the lift test that are observed are not exact measurements and are expected to have some noise. The Gmma distribution is used to model this noise by default. This choice is partly arbitrary but makes more sense as the saturation curve is montonic making increase in media correspond to an increase in target (positive lift). A decrease in media is assumed to have a negative lift.

Let me know if that helps. I can provide some more details if you have more specific questions.

**Comment by wd60622** [comment]
> 1. ... minimize the difference between the observed slope from the tests and what results from the saturation function

This sounds like a pretty good summary of the methodology!

> 2. In practice does this only inform the part of the saturation curves around x0 and x1?

It informs the whole curve because know the slope (or approximate slope) around x0 and x1 also restricts other sections of the curve.

> 3. If in the case I noted in another question where we only have industry benchmarks of the contribution / investment for channels, would the way to try and conform that into a lift test be to set x0 = 0 and x1 = mean spend in a period for the channel and delta_y be the value that would result in the benchmark ROAS we have?

If 0 to average spend is how you interpret those numbers, then I think that is reasonable way to incorporate. I am not sure how "industry benchmarks" are defined. Maybe @cetagostini has some input
