### ISSUE TITLE
Docs version switch button hidden until one scrolls to the end of page

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#264]
https://www.pymc-marketing.io/en/latest/notebooks/mmm/mmm_example.html

![image](https://user-images.githubusercontent.com/28983449/235671548-c34831ba-470c-43ac-9141-bf7d2c8e8aa0.png)

![image](https://user-images.githubusercontent.com/28983449/235671588-81fb7895-8524-4d8e-9f9b-3cb4b382ac8f.png)

**Comment by wd60622** [comment]
Bizarre. Some things that I have noticed: 

- [PyMC docs work as intended](https://www.pymc.io/projects/docs/en/stable/api.html)
- PyMC docs has footer show only at bottom. PyMC-Marketing footer shows the whole time
- footer seems to be the blocking element

Comparison of the versions

| Docs | Sphinx Version | PyData Sphinx Theme Version |
|--------|--------|--------|
| PyMC | 7.3.7 | 0.14.4 |
| PyMC-Marketing | 7.3.7 | 0.15.3 | 

Don't think it is a version think since latest PyData Sphinx doesn't have this issue

The footer has class name `bd-footer`
