### ISSUE TITLE
Recency in `clv.utils.clv_summary()`

### ISSUE THREAD

**Issue by matthias-Q** [pymc-labs/pymc-marketing#304]
I was wondering if the definition of recency is correct. According to the paper of Hardie (http://brucehardie.com/notes/008/pareto_nbd_MATLAB.pdf) recency is defined as: 

> his “recency” (when his last transaction occurred)

However in this function (also in the function of the lifetimes package) "recency" is the timespan between the first and the last purchase.

So shouldn't be recency be `recency = observation_period_end - max(transaction_date)` rather than `recency = max(transaction_date) - min(transaction_date)` ?

**Comment by ColtAllen** [comment]
Hey @matthias-Q,

The definition of `recency` you proposed is used in [RFM Analysis](https://www.techtarget.com/searchdatamanagement/definition/RFM-analysis), which I'm considering implementing into `pymc-marketing` because it'd be useful for cohort studies.

For BTYD modeling however, time between transactions is one of the key aspects we're trying to capture, hence the timespan definition of `recency`. This fits Hardie's definition because with any given customer, `T=0 for min(transaction_date)`  so `recency` indicates the time period when the last transaction occurred.

Speaking of Hardie, @juanitorduz has actually been in contact with him about this library, and he's very interested in the progress we're making.

**Comment by matthias-Q** [comment]
Thanks for the quick answer. I think I understand. Technically, the different definitions contain the same information.

What I find confusing, that all of the BTYD papers also use the recency definition that I mentioned above (time since last interaction)

https://cran.r-project.org/web/packages/BTYD/vignettes/BTYD-walkthrough.pdf
http://brucehardie.com/papers/018/fader_et_al_mksc_05.pdf

**Comment by ColtAllen** [comment]
Different definitions for the same term in this domain of modeling can definitely cause some confusion. However, I don't see any discrepancies in how the papers define recency. Quoted from BTYD-walkthrough.pdf:

> We have to keep track of a
“time zero” as a point of reference for recency and total time observed

"Time zero" is referring to the customer's first purchase. If they did not make any repeat purchases, then `recency` will also be zero.

Time since last interaction is valuable for bucketing customers in RFM analysis because recent purchases suggest the customer is still active. However, total time observed is just the end date of the study period, chosen by the researcher. We need to know the customer's recency relative to their first purchase for predictive modeling.

**Comment by ColtAllen** [comment]
If there are no further questions, I'm gonna go ahead and close this.
