### ISSUE TITLE
After 0.2.0 update an error in the fit function. Is there a new definition to run the fit?

### ISSUE THREAD

**Issue by SiebertLooijeAtBillyGrace** [pymc-labs/pymc-marketing#336]
A very good morning,

This morning we had some issues with using your package (going from 0.1.1 to 0.2.0). Apparently the fit function expects to have now a X parameter, which was not needed before?

<img width="809" alt="image" src="https://github.com/pymc-labs/pymc-marketing/assets/112629564/b7b0a952-8ffe-4574-a011-b946acf48904">

Is there a new way of using the fit function?

This is the piece of code which gives now an issue. For now we are switching back to 0.1.1

```
mmm = DelayedSaturatedMMM(
            data=df,
            target_column="sessions",
            date_column="date",
            channel_columns=channel_columns,
            control_columns=[
                "day",
                "sessions_lag",
                "t",
            ],
            adstock_max_lag=8
        )
mmm.fit(target_accept=0.95, chains=2, random_seed=2)
```

Thanks for this library!

**Comment by ricardoV94** [comment]
Hi, yes there was a big change to make the API a bit closer to scikit-learn and to allow saving and loading models.

The updated MMM notebook example shows the new API: https://www.pymc-marketing.io/en/stable/notebooks/mmm/mmm_example.html#id1

And the saving and loading functionality is described here: https://www.pymc-marketing.io/en/stable/guide/benefits/model_deployment.html

Because we're still in an early state (version <1) the API is still subject to change. We're trying to get it right before we freeze it.

If you are doing production or sensitive work we suggest you pin your dependency versions in a `>=0.x, <0.x+1` range, which will include only bugfixes but no breaking changes
