### ISSUE TITLE
Forward pass on a given spend 

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#451]
I've been playing around with how some amount of money contributes to the upcoming sales in order to understand the adstock functions. I wonder if others have used this to build intuition of the model fit. 

The general sense of the function is 

```python
def new_spends_contributions(spends: np.ndarray, mmm: DelayedSaturatedMMM, spends_leading_up: np.array = None) -> xarray.core.dataarray.DataArray: 
    """
    Args: 
        spends: vector of new spends for all the channels
        mmm: model but would be self if a method 
        spends_leading_up: vector of spends in the weeks leading up for each channel that are carried over via adstock function 
    Returns: 
        Forward pass of contributions for the next coming weeks for each channel. (draw, channel, weeks_since_spend)
    """
```

This evaluates the adstock, the saturation, beta coefficient, (and does the inverse transform)

It doesn't give a good sense of the saturation of a spend unless it is evaluated across different spends, but I think it give some intuition on how long (and how much) a certain amount goes because of the adstock function. 

Here is an example visualiation based on this data that compares two different spends. For instance, I see both channels spends last ~ 4 weeks. I don't think there are currently any cuts of the parameters that would show this specifically

<img width="1270" alt="this-weeks-spend" src="https://github.com/pymc-labs/pymc-marketing/assets/57733339/fcd0c29e-8a05-468b-b496-cbc99c472663">

I would love to hear any thoughts and if this would be helpful to understand adstocks after fit (especially if more will be added to the mix eventually #447)

**Comment by cetagostini** [comment]
Hey hey!

In my opinion, this information is incredibly useful - perhaps even tremendously useful. I was looking to dedicate some time to this myself, so seeing that you have already found a way to apply it is fantastic.

This graph is particularly helpful to me because it allows me to estimate how many incremental sales occur at a certain level of spending. With this prior information, I can generate experiments to update my beliefs. 

Additionally, by looking at this graph, I can easily assess how well the model estimates this effect. Ultimately, we are working with two transformations and beta, and I have had times where delivering priors of a specific transformation caused the model to compensate by adjusting another transformation in which it doesn't have strong priors. 

Most importantly, I see this graph as a straightforward way to explain this concept to people who are not familiar with MMM. If I were to show this to my stakeholders tomorrow, they would be able to understand it easily.

It's quite a secret you've kept, Haha! If you need any help, I'd be happy to lend a hand with putting this PR out. We could even show it before the next release (?)... Perhaps to optimistic.

cc: @wd60622

**Comment by wd60622** [comment]
Completed with #456
