### ISSUE TITLE
 Inquiry Regarding Definition of Recency in pymc-marketing Package

### ISSUE THREAD

**Issue by sarim-zafar** [pymc-labs/pymc-marketing#583]
Dear pymc-marketing Maintainers,

I hope this message finds you well. I have been exploring the functionalities of the pymc-marketing package and came across a slight discrepancy in the definition of "recency" when compared to other commonly used RFM (Recency, Frequency, Monetary) analysis methods.

In the sample notebooks provided with the package, recency is defined as: "the age of the customer when they made their most recent purchases. This is equal to the duration between a customer’s first purchase and their latest purchase." However, in other materials discussing RFM analysis, including widely used resources online, recency is defined as: "the number of days between the present date and the date of the last purchase made by each customer."

This variance in definitions has led to some confusion. I would like to inquire which definition of recency is considered appropriate within the context of the pymc-marketing package. Understanding this clarification would greatly aid users in effectively utilizing the package for RFM analysis and related tasks.

Could you please provide insights into why there is a difference in the definition of recency within the package and which definition aligns with the intended usage of the package?

Thank you very much for your time and assistance. I look forward to your response.

Best regards

**Comment by ColtAllen** [comment]
Hey @sarim-zafar,

Recency as explained in the Quickstart is the definition used for modeling, which is a separate area from RFM analysis despite similar aggregation methods. `pymc-marketing` currently doesn't support RFM analysis, but it is a capability I'm looking to add soon.

This issue is identical to https://github.com/pymc-labs/pymc-marketing/issues/304, which contains some links to research papers containing more information.

**Comment by sarim-zafar** [comment]
Thank you for providing the clarification
