### ISSUE TITLE
0.6.0 breaks the mmm_example notebook

### ISSUE THREAD

**Issue by soulforger0** [pymc-labs/pymc-marketing#795]
Hi Guys

I was looking a the latest mmm_example.ipynb and runing it cell by cell with no code change. and encounter the following error. do anyone know what might be the issue? 
Thanks!

![image](https://github.com/pymc-labs/pymc-marketing/assets/27894081/6da4f1ed-645e-4835-8668-f1cefabd3e2d)

watermark:
Python implementation: CPython
Python version       : 3.10.0
IPython version      : 8.26.0

pytensor: 2.23.0

arviz     : 0.18.0
numpy     : 1.23.5
matplotlib: 3.9.0
pymc      : 5.16.1
pandas    : 2.2.2
seaborn   : 0.13.2

Watermark: 2.4.3

**Comment by wd60622** [comment]
Hi @soulforger0 

The notebooks require the latest state of the code base. So if you take notebook from main branch, then you will likely need main branch installed in order to run. 
There are some big changes since 0.6.0 so you'd have to use the 0.6.0 notebook (bottom left corner of docs or github tag) with 0.6.0 installed. 

If you have any issues with the notebook with the dev version (main branch) installed, let us know

**Comment by soulforger0** [comment]
Thanks @wd60622 
the 0.6.0 version notebook is working.

used https://github.com/pymc-labs/pymc-marketing/blob/0.6.0/docs/source/notebooks/mmm/mmm_example.ipynb
