### ISSUE TITLE
List of Continuous, Non-Contractual `clv` Models to Consider Adding

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#91]
https://github.com/mplatzer/BTYDplus

**Comment by ColtAllen** [comment]
These are the models in question:

>  **NBD** Ehrenberg, Andrew SC. "The pattern of consumer purchases." Applied Statistics (1959): 26-41. \doi{10.2307/2985810}

I don't think this model is worth implementing. This was the forerunner of the ParetoNBD model, and models purchase variability within a fixed time period. It does not have the 'death' component of ParetoNBD and related models. 

> **MBG/NBD** Batislam, E.P., M. Denizel, A. Filiztekin. 2007. Empirical validation and comparison of models for customer base analysis. International Journal of Research in Marketing 24(3) 201–209. \doi{10.1016/j.ijresmar.2006.12.005}

We have an issue for this: https://github.com/pymc-labs/pymc-marketing/issues/94
I've also been wondering if this could be expanded for covariates per the PDF in https://github.com/pymc-labs/pymc-marketing/issues/134 

> **(M)BG/CNBD-k** Reutterer, T., Platzer, M., & Schroeder, N. (2020). "Leveraging purchase regularity for predicting customer behavior the easy way." International Journal of Research in Marketing. \doi{10.1016/j.ijresmar.2020.09.002}

These two models are worth implementing. They add an additional hierarchical distribution for purchase rates to the BG/NBD and MBG/NBD models.

http://www.reutterer.com/papers/reutterer&platzer&schroeder_2021.pdf

 1. While active, the purchases of customers occur with Erlang-k-distributed waiting times, with rate parameter λ and integer-valued regularity parameter k.
 2. Heterogeneity in λ follows a gamma distribution with shape parameter r and rate parameter α across customers.

> **Pareto/NBD** (HB) Ma, Shao-Hui, and Jin-Lan Liu. "The MCMC approach for solving the Pareto/NBD model and possible extensions." Natural Computation, 2007. ICNC 2007. Third International Conference on. Vol. 2. IEEE, 2007. \doi{10.1109/ICNC.2007.728}
> **Pareto/NBD** (Abe) Abe, Makoto. "Counting your customers one by one: A hierarchical Bayes extension to the Pareto/NBD model." Marketing Science 28.3 (2009): 541-553. \doi{10.1287/mksc.1090.0502}

This paper compares both models, and the "Abe" model is superior:
https://link.springer.com/article/10.1007/s11573-021-01057-6

It adds an additional hierarchical distribution for the death rate, and according to the paper can even model individuals and populations simultaneously! I may end up implementing this if the [hyp2f1 gradients in the ParetoNBD model prove too troublesome.](https://github.com/pymc-labs/pymc-marketing/issues/127)

> **Pareto/GGG** Platzer, Michael, and Thomas Reutterer. "Ticking Away the Moments: Timing Regularity Helps to Better Predict Customer Activity." Marketing Science (2016). \doi{10.1287/mksc.2015.0963}

This model is only at the individual level and is fitted to raw transactions rather than the frequency/recency/T summary format. I've been interested in adding it for a while.

The [CLVTools](https://github.com/bachmannpatrick/CLVTools) R library also has a few other models to consider: 

> Standard Gamma/Gompertz/NBD (Bemmaor & Glady 2012)
> Gamma/Gompertz/NBD model with time-invariant contextual factors (Näf, Bachmann & Meierer 2020)

I've tried looking for a PDF, but these research papers are behind a paywall.

> Pareto/NBD model with time-varying contextual factors (Bachmann, Meierer & Näf 2021)

This model appears to be extremely computationally intensive, but is worth exploring further.
https://www.zora.uzh.ch/id/eprint/197236/1/mksc.2020.1254.pdf

There is also a PDF on adding time-varying covariates to the BG/NBD model. Like the Pareto/GGG, it is fitted to raw transactions:
https://www.brucehardie.com/notes/040/time-varying_covariates_in_BGNBD.pdf

The Periodic Death Opportunity (PDO) model was mentioned in a `lifetimes` issue last year:
https://github.com/CamDavidsonPilon/lifetimes/issues/427

And lastly, if you want to try something completely different and use Gaussian Processes:
https://www0.gsb.columbia.edu/mygsb/faculty/research/pubfiles/26107/ansari_Bayesian_Nonparametric.pdf

Whew, I think that covers just about every continuous non-contractual model worth implementing 😅

**Comment by zwelitunyiswa** [comment]
@ColtAllen The Gamma/Gompertz/NBD model with time-invariant contextual factors (Näf, Bachmann & Meierer 2020) paper is here: https://pubsonline.informs.org/doi/epdf/10.1287/mksc.2020.1254

I also have the Standard Gamma/Gompertz/NBD (Bemmaor & Glady 2012) paper. I can give it to you via email or DM.

**Comment by zwelitunyiswa** [comment]
@ColtAllen Check your LinkedIn inbox.

**Comment by ColtAllen** [comment]
Thanks @zwelitunyiswa!

**Comment by ColtAllen** [comment]
Pinning this because it's a good list of models to add to the `clv` module. Also added a link to another paper comparing the Pareto/NBD, BetaGeo/NBD, PDO and Bayesian Pareto/NBD Abe models.

**Comment by larryshamalama** [comment]
There's a lot of models that seem available, each with a different paper. Perhaps it would be good to find a way to harmonize all the models in a table or some sort of documentation?

**Comment by ColtAllen** [comment]
> #134

That's a good idea. Do you think it's worth adding to the official documentation?

**Comment by larryshamalama** [comment]
> That's a good idea. Do you think it's worth adding to the official documentation?

If I can find a clever and intuitive way of summarizing the models 😅 Something that I will have to think about...

**Comment by ColtAllen** [comment]
> > That's a good idea. Do you think it's worth adding to the official documentation?
> 
> If I can find a clever and intuitive way of summarizing the models 😅 Something that I will have to think about...

I edited my OP so it's more coherent. The official documentation should focus on differences between these models and appropriate use cases methinks.

**Comment by ColtAllen** [comment]
Updated OP to add issue link for generalized seasonality.
