### ISSUE TITLE
Implement Modified BetaGeo Model

### ISSUE THREAD

**Issue by ricardoV94** [pymc-labs/pymc-marketing#94]
Very similar to #67, except it allows for dropout before the first purchase: https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/fitters/modified_beta_geo_fitter.py

**Comment by ColtAllen** [comment]
I built this model for my [`btyd`](https://github.com/ColtAllen/btyd/blob/main/btyd/models/mod_beta_geo_model.py) library way back in 2022. It sacrifices performance (both in speed and posterior estimation) so that non-repeat customers can have an alive probability < 1. I don't consider this trade-off worthwhile given the effort required to implement this model, and won't be working on it. That being said, if anyone else wishes to do so, they're more than welcome.
